### ISSUE TITLE
Support StyleSheet.create()

### ISSUE THREAD

**Issue by edencakir** [hummingbird-me/kitsu-mobile#14]
update NativeBase to **2.3.0**, and create all style objects with `StyleSheet.create({})`

> Performance:
> 
> Making a stylesheet from a style object makes it possible to refer to it by ID instead of creating a new style object every time.
> It also allows to send the style only once through the bridge. All subsequent uses are going to refer an id (not implemented yet).

[Issue 1](https://github.com/GeekyAnts/NativeBase/issues/884)
[Issue 2](https://github.com/GeekyAnts/NativeBase/issues/575)
[Issue 3 which points the correct version](https://github.com/GeekyAnts/NativeBase/issues/993)

**Comment by BilalBudhani** [comment]
This is a good update but NativeBase 2.3.0 requires React Native >= 0.46, so first we will need to target that.
