### ISSUE TITLE
Refresh token, how?

### ISSUE THREAD

**Issue by hu9osaez** [hummingbird-me/kitsu-mobile#140]
Hello!

I'm following the development of your app for a while and seeing the code I doubt arises of when the `access_token` obtained is refreshed.

How is the work flow of this? 

Thanks in advance.

**Comment by Mikunj** [comment]
Hey @hu9osaez, the authentication and token handling is all done by a [third party library](https://github.com/mulesoft/js-client-oauth2) using the Resource Owner Password Credentials Grant.

**Comment by Mikunj** [comment]
Hey @hu9osaez, thanks for reminding us to put that in, i replied to your issue before but i realised that we didn't actually have that functionality in.

I've submitted a PR (#146) with the changes for the token refresh 👍

**Comment by NuckChorris** [comment]
We now properly refresh the token 🎉

**Comment by Mikunj** [comment]
@hu9osaez you can find the relevant code here:
https://github.com/hummingbird-me/kitsu-mobile/blob/master/src/config/middlewares.js
