### ISSUE TITLE
App removed from play store

### ISSUE THREAD

**Issue by LHJ** [hummingbird-me/kitsu-mobile#432]
The app seems to have been removed from the play store on Android. I can no longer find it when searching.

**Comment by tomgus1** [comment]
Seems to be back on the Play Store today

**Comment by NuckChorris** [comment]
Awesome! I tried to fix it but I couldn't find the email they sent us so I just had to go fix anything with a ⚠️ by it

Looks like they wanted an age rating from us, sorry about that!
