### ISSUE TITLE
Request: F-Droid support

### ISSUE THREAD

**Issue by Soundtoxin** [hummingbird-me/kitsu-mobile#442]
Could you please list this app on [F-Droid](https://f-droid.org/)? It's a repository of [free (as in freedom) software](https://en.wikipedia.org/wiki/Free_software) apps. Your license is already a free software license, so hopefully it would be easy to list it on there. I get 99% of my apps from there, but I have to get the Kitsu app via the aurora store (alternative front-end for the play store). I would love it if the Kitsu app were on F-Droid!

**Comment by NuckChorris** [comment]
We've looked into it previously, but it has a lot of onerous requirements on developers that we simply cannot meet without significant work:

- Builds must be done using their own system
  - We use React Native and Expo which have their own build systems
- All libraries must be FLOSS (we have thousands of dependencies, we cannot reasonably audit all of that)
  - This applies even to ad libraries and Google Play Services

While we are 100% Libre, we just don't have the manpower to maintain an entire separate build toolchain and patchsets just for one app store ☹️  Sorry

**Comment by Soundtoxin** [comment]
Ah, that's a huge bummer. Thanks for the response. I guess this is a matter of won't-fix then. I'll close the issue.

**Comment by heiwiper** [comment]
Does [this](https://f-droid.org/en/2020/10/14/adding-react-native-app-to-f-droid.html)  solve the first obstacle ?

**Comment by wopian** [comment]
> Does [this](https://f-droid.org/en/2020/10/14/adding-react-native-app-to-f-droid.html) solve the first obstacle ?

Thank you for this. For 2), It also seems over 1,300 of the package dependencies are MIT with ~40 with no, or custom, licenses we would need to audit ourselves.

Reference: https://gitlab.com/fdroid/fdroiddata/-/blob/f58cb89b47091e1d307f96595cbb9968707764db/metadata/com.etesync.notes.yml
