### ISSUE TITLE
iOS14 and Clipboard Access

### ISSUE THREAD

**Issue by KyleKing** [hummingbird-me/kitsu-mobile#445]
I see a notification that Kitsu read the clipboard contents. Is this intended behavior in Kitsu or is a dependency doing this? From the app source, it didn't appear to be expected behavior. Is this related to the removal of the Kitsu app from the US store?

![IMG_6373](https://user-images.githubusercontent.com/3784339/93544349-e0e16800-f92b-11ea-8efe-21c2ecc2a3e2.PNG)

**Update**: Kitsu was taken off of the App Store, so this might have been related?

**Comment by Reinachan** [comment]
I belive it's a dependency doing this. A rework of the app is being worked on but it takes time. But when we get that working, we can look into fixing that. For now tho, you can rest assure that we're not snooking into the sketchy stuff you copied to the clipboard yesterday ;)

The app being off the app store was related to a false copyright dispute over the logo. It has been resolved and the app is back on the App Store again now :)
