### ISSUE TITLE
Need Updated Readme

### ISSUE THREAD

**Issue by nolanblew** [hummingbird-me/kitsu-mobile#446]
## Building Errors

Current readme's instructions for building, running, and debugging the app no longer work with the new default `expo` branch. 

Current issues I have while trying to run `expo`:
 - Running `yarn start:reset` no longer works. It produces the error:
![image](https://user-images.githubusercontent.com/1565705/109858852-31662c80-7c11-11eb-8790-4a9540072aee.png)

  - Ignoring that, trying to run `yarn start` will start expo with the following dependency error:
![image](https://user-images.githubusercontent.com/1565705/109858497-c288d380-7c10-11eb-855a-445efca19f82.png)

And in the console:
![image](https://user-images.githubusercontent.com/1565705/109856884-df240c00-7c0e-11eb-889b-c93555e8853a.png)

 - Attempting to run the app in the android emulator results in a 500 erorr:

<img src="https://user-images.githubusercontent.com/1565705/109857260-5c4f8100-7c0f-11eb-8bd0-3173a2c992e5.png" width="255px" />

  And in the console:
![image](https://user-images.githubusercontent.com/1565705/109857387-7b4e1300-7c0f-11eb-8778-c65eff8c09f5.png)

 - Attempting to upgrade the `expo-random` package by using `expo install expo-random` (using the `update` or `upgrade` option always tries to force an upgrade of the expo SDK as well) makes all errors and warning go away, but running the app leaves a blank screen:
 
<img src="https://user-images.githubusercontent.com/1565705/109857900-07f8d100-7c10-11eb-8c47-2c466dfcac6d.png" width="255px" />

## Setup
I'm running this on Windows Subsystem for Linux (Ubuntu 20.04.01 LTS) with 64GB of RAM and i7 10th gen processor. I've also tried running this on a computer running the same version of Ubuntu as the OS with the same results. I do not have access to a Mac.

## Default Branch
Also, I'm not sure if we should be using the `expo` branch as the base branch. 

I think both the README.md and the [Deployment Wiki Page](https://github.com/hummingbird-me/kitsu-mobile/wiki/App-Deployment) may need to be updated

**Comment by NuckChorris** [comment]
Sorry about that, we're working on moving the app from React Native to Expo, and moving from Yarn to NPM, and I hadn't updated the README yet. I've updated it now, and verified that it runs on Windows, even without WSL!

**Comment by nolanblew** [comment]
> Sorry about that, we're working on moving the app from React Native to Expo, and moving from Yarn to NPM, and I hadn't updated the README yet. I've updated it now, and verified that it runs on Windows, even without WSL!

Awesome! Looking forward to the new move
