### ISSUE TITLE
Error of Unable to resolve module

### ISSUE THREAD

**Issue by adityaraval** [hummingbird-me/kitsu-mobile#97]
React packager ready.

Loading dependency graph, done.
Bundling `index.ios.js`  13.7% (435/1175), failed.
error: bundling failed: "Unable to resolve module `../../../node_modules/react-native/src/store/types` from `/Users/apple/Desktop/kitsu-mobile/src/store/feed/actions.js`: could not resolve `/Users/apple/Desktop/kitsu-mobile/node_modules/react-native/src/store/types' as a folder: it did not contain a package, nor an index file"
![screen shot 2017-11-17 at 6 59 53 pm](https://user-images.githubusercontent.com/6738371/32949826-34525770-cbca-11e7-9465-8515197a77f5.png)

**Comment by edencakir** [comment]
Reset your packager. yarn start:reset

**Comment by edencakir** [comment]
You can verify that with this line: `node node_modules/react-native/local-cli/cli.js start --reset-cache` (make sure you see this)

<img width="635" alt="screen shot 2017-11-17 at 4 53 56 pm" src="https://user-images.githubusercontent.com/6555480/32950608-f3cc8890-cbb7-11e7-987e-0b1b931f138d.png">

**Comment by adityaraval** [comment]
Thanks, I am able to run it now. 👍
